// //////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
//
// It is automatically generated by generate-dtos.js
// //////////////////////////////////////////////////////////////////////////

import { BidtPackageOperationIdDTO } from './bidt-package-operation-id-dto.interface';

export interface BidtPackageOperationDTO extends BidtPackageOperationIdDTO {
  bidtPackage: string;

  bidtQualification?: string;
  packopeCode?: string; // 50
  packopeDesignation?: string; // 100
  packopeStatus?: string; // 50
  bidtDfTypeOperationId: number;
  bidtPackageId: number;
}
