// //////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
//
// It is automatically generated by generate-dtos.js
// //////////////////////////////////////////////////////////////////////////

import { BidtDfItemOperationIdDTO } from './bidt-df-item-operation-id-dto.interface';

export interface BidtDfItemOperationDTO extends BidtDfItemOperationIdDTO {
  bidtDfItem: string;

  bidtQualification?: string;
  dfioCode?: string; // 50
  dfioDesignation?: string; // 100
  dfioStatus?: string; // 50
  bidtDfTypeOperationId: number;
}
