import { BidoCustomerDTO } from './bido-customer-dto.interface';
import { BidoEquipmentDTO } from './bido-equipment-dto.interface';

export interface HBidoEquipmentDTO {
  equipmentCode?: string;
  familyVariantCode?: string;
  equEquipmentCode?: string;
  owner?: BidoCustomerDTO;
  operator?: BidoCustomerDTO;
  ownerCustomerCode?: string;
  pn?: string;
  operatorCustomerCode?: string;
  sn?: string;
  snManufacturer?: string;
  equipmentDesignation?: string;
  equipmentFunction?: string;
  manufacturingDate?: Date;
  chapter?: string;
  section?: string;
  subject?: string;
  sheet?: string;
  marks?: string;
  equiPosition?: string;
  sentence?: string;
  manufacturingConfiguration?: boolean;
  functionCode?: string;
  zone?: string;
  country?: string;
  registration?: string;
  eisDate?: Date;
  lifeRestriction?: boolean;
  familyCode?: string;
  ratingCode?: string;
  timestamp?: number;
  action?: string;
  operationalStatus?: string;
  modelCode?: string;
  statusState?: string;
  statusUser?: string;
  statusDate?: Date;
  currentBidoEquipmentData?: BidoEquipmentDTO;
}
