import { BireDamLocTaskDTOId } from '../../api-types/bire-dam-loc-task-dto-id.interface';
import { BireDamLocTaskDTO } from '../../api-types/bire-dam-loc-task-dto.interface';
import { BireDamageItemDTOId } from '../../api-types/bire-damage-item-dto-id.interface';
import { BireDamageItemDTO } from '../../api-types/bire-damage-item-dto.interface';
import { BireDocItemDTO } from '../../api-types/bire-doc-item-dto.interface';
import { BireDocumentDTO } from '../../api-types/bire-document-dto.interface';
import { BireItemAttributeDTO } from '../../api-types/bire-item-attribute-dto.interface';
import { BireItemDTO } from '../../api-types/bire-item-dto.interface';
import { BireItemItemDTOId } from '../../api-types/bire-item-item-dto-id.interface';
import { BireItemItemDTO } from '../../api-types/bire-item-item-dto.interface';
import { BireItemMaintenanceDTOId } from '../../api-types/bire-item-maintenance-dto-id.interface';
import { BireItemMaintenanceDTO } from '../../api-types/bire-item-maintenance-dto.interface';
import { BireItemSiteDTOId } from '../../api-types/bire-item-site-dto-id.interface';
import { BireItemSiteDTO } from '../../api-types/bire-item-site-dto.interface';
import { BireItemVersionDTOId } from '../../api-types/bire-item-version-dto-id.interface';
import { BireItemVersionDTO } from '../../api-types/bire-item-version-dto.interface';
import { BireLocalisationItemDTOId } from '../../api-types/bire-localisation-item-dto-id.interface';
import { BireLocalisationItemDTO } from '../../api-types/bire-localisation-item-dto.interface';
import { BirePackBaseOptionDTOId } from '../../api-types/bire-pack-base-option-dto-id.interface';
import { BirePackBaseOptionDTO } from '../../api-types/bire-pack-base-option-dto.interface';
import { BirePackEvolutionDTO } from '../../api-types/bire-pack-evolution-dto.interface';
import { BireReturnItemDTOId } from '../../api-types/bire-return-item-dto-id.interface';
import { BireReturnItemDTO } from '../../api-types/bire-return-item-dto.interface';
import { BireTaskItemDTOId } from '../../api-types/bire-task-item-dto-id.interface';
import { BireTaskItemDTO } from '../../api-types/bire-task-item-dto.interface';
import { BireTilItemDTOId } from '../../api-types/bire-til-item-dto-id.interface';
import { BireTilItemDTO } from '../../api-types/bire-til-item-dto.interface';
import { BireVersionMeasureDTOId } from '../../api-types/bire-version-measure-dto-id.interface';
import { BireVersionMeasureDTO } from '../../api-types/bire-version-measure-dto.interface';
import { BireVersionPnDTOId } from '../../api-types/bire-version-pn-dto-id.interface';

export interface SaveItemInput {
  bireItemDTO: BireItemDTO;
  saveStructureTab?: BireItemItemDTO[];
  removeDataStructureTab?: BireItemItemDTOId[];
  bireTaskItemAddedList?: BireTaskItemDTO[];
  bireTaskItemDeletedList?: BireTaskItemDTOId[];
  bireLocalisationItemDTOAddedList?: BireLocalisationItemDTO[];
  bireLocalisationItemDTOUpdatedList?: BireLocalisationItemDTO[];
  bireLocalisationItemDTOIdRemoveList?: BireLocalisationItemDTOId[];
  bireDamageItemDTOAddedList?: BireDamageItemDTO[];
  bireDamageItemDTOIdRemoveList?: BireDamageItemDTOId[];
  bireTilItemDTOAddedList?: BireTilItemDTO[];
  bireTilItemDTODeletedList?: BireTilItemDTOId[];
  bireReturnItemDTOAddedList?: BireReturnItemDTO[];
  bireReturnItemDTODeletedList?: BireReturnItemDTOId[];
  bireItemSiteDTOAddedList?: BireItemSiteDTO[];
  bireItemSiteDTODeletedList?: BireItemSiteDTOId[];
  bireItemMaintenanceDTOAddedList?: BireItemMaintenanceDTO[];
  bireItemMaintenanceDTOUpdatedList?: BireItemMaintenanceDTO[];
  bireItemMaintenanceDTODeletedList?: BireItemMaintenanceDTOId[];
  bireItemVersionDTOAddedList?: BireItemVersionDTO[];
  bireItemVersionDTODeletedList?: BireItemVersionDTOId[];
  bireItemAttributeDTOList?: BireItemAttributeDTO[];
  createBireVersionMeasureDTOList?: BireVersionMeasureDTO[];
  updateBireVersionMeasureDTOList?: BireVersionMeasureDTO[];
  createBireDamLocTaskDTOList?: BireDamLocTaskDTO[];
  removeBireDamLocTaskDTOIdList?: BireDamLocTaskDTOId[];
  removeBireVersionMeasureDTOIdList?: BireVersionMeasureDTOId[];
  bireVersionPnDTOIdDeletedList?: BireVersionPnDTOId[];
  bireItemSiteDTOUpdatedList?: BireItemSiteDTO[];
  documentsAdded?: BireDocItemDTO[];
  documentsUpdated?: BireDocumentDTO[];
  documentsRemoved?: BireDocumentDTO[];
  isCreate: boolean;
  createBirePackBaseOptionList?: BirePackBaseOptionDTO[];
  updateBirePackBaseOptionList?: BirePackBaseOptionDTO[];
  removeBirePackBaseOptionList?: BirePackBaseOptionDTOId[];
  createBirePackEvolutionDTOList?: BirePackEvolutionDTO[];
  updateBirePackEvolutionDTOList?: BirePackEvolutionDTO[];
  packBaseOptionCode?: string[];
}
